name: PR Checklist validator
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: Mrkristal/require-checklist-action@v0.0.3
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
