name: Require Checklist
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
