name: 'PR Tasks Completed Check'
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: Mrkristal/required-task-checker-action@0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
